spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true

logging:
  level:
#    org.springframework.security: 'INFO'






